export const ERROR_CODES = {
    GAME_NOT_FOUND: "GAME_NOT_FOUND",
    ERR_SIGNAL_LOST: "ERR_SIGNAL_LOST",
    ERR_FULL_CAPACITY: "ERR_FULL_CAPACITY",
    ERR_INVALID_ALIAS: "ERR_INVALID_ALIAS",
    ERR_INVALID_SIGNATURE: "ERR_INVALID_SIGNATURE",
    ERR_INVALID_STATE: "ERR_INVALID_STATE",
    ERR_NO_PLAYERS: "ERR_NO_PLAYERS",
    ERR_INVALID_ROLE: "ERR_INVALID_ROLE",
    ERR_INVALID_DURATION: "ERR_INVALID_DURATION",
    ERR_NO_QUESTS: "ERR_NO_QUESTS",
    ERR_QUEST_LOAD_FAILED: "ERR_QUEST_LOAD_FAILED",
    ERR_QUEST_COMPLETE_FAILED: "ERR_QUEST_COMPLETE_FAILED",
    // Authentication error codes
    ERR_INVALID_INPUT: "ERR_INVALID_INPUT",
    ERR_SERVER_CONFIG: "ERR_SERVER_CONFIG",
    ERR_INVALID_CREDENTIALS: "ERR_INVALID_CREDENTIALS",
    ERR_NO_SESSION: "ERR_NO_SESSION",
    ERR_INVALID_SESSION: "ERR_INVALID_SESSION",
    // Batch management error codes
    ERR_NOT_FOUND: "ERR_NOT_FOUND",
    ERR_UNAUTHORIZED: "ERR_UNAUTHORIZED",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
