export const ERROR_CODES = {
    GAME_NOT_FOUND: "GAME_NOT_FOUND",
    ERR_SIGNAL_LOST: "ERR_SIGNAL_LOST",
    ERR_FULL_CAPACITY: "ERR_FULL_CAPACITY",
    ERR_INVALID_ALIAS: "ERR_INVALID_ALIAS",
    ERR_INVALID_SIGNATURE: "ERR_INVALID_SIGNATURE",
    ERR_GAME_ALREADY_STARTED: "ERR_GAME_ALREADY_STARTED",
    ERR_PLAYER_ALREADY_CONNECTED: "ERR_PLAYER_ALREADY_CONNECTED",
    ERR_LOGIN_REQUIRED_FOR_AUTH_PLAYER: "ERR_LOGIN_REQUIRED_FOR_AUTH_PLAYER",
    ERR_INVALID_STATE: "ERR_INVALID_STATE",
    ERR_NO_PLAYERS: "ERR_NO_PLAYERS",
    ERR_INVALID_ROLE: "ERR_INVALID_ROLE",
    ERR_INVALID_DURATION: "ERR_INVALID_DURATION",
    ERR_NO_QUESTS: "ERR_NO_QUESTS",
    ERR_QUEST_LOAD_FAILED: "ERR_QUEST_LOAD_FAILED",
    ERR_QUEST_COMPLETE_FAILED: "ERR_QUEST_COMPLETE_FAILED",
    ERR_QUEST_NOT_ASSIGNED: "ERR_QUEST_NOT_ASSIGNED",
    // Authentication error codes
    ERR_INVALID_INPUT: "ERR_INVALID_INPUT",
    ERR_SERVER_CONFIG: "ERR_SERVER_CONFIG",
    ERR_INVALID_CREDENTIALS: "ERR_INVALID_CREDENTIALS",
    ERR_NO_SESSION: "ERR_NO_SESSION",
    ERR_INVALID_SESSION: "ERR_INVALID_SESSION",
    // Batch management error codes
    ERR_NOT_FOUND: "ERR_NOT_FOUND",
    ERR_UNAUTHORIZED: "ERR_UNAUTHORIZED",
    // Meeting error codes
    ERR_MEETING_ACTIVE: "ERR_MEETING_ACTIVE",
    ERR_MEETING_NOT_ACTIVE: "ERR_MEETING_NOT_ACTIVE",
    ERR_MEETING_ALREADY_USED: "ERR_MEETING_ALREADY_USED",
    ERR_MEETING_VOTE_INVALID: "ERR_MEETING_VOTE_INVALID",
    ERR_MEETING_FORBIDDEN: "ERR_MEETING_FORBIDDEN",
    ERR_MEETING_BLOCKED_BY_SABOTAGE: "ERR_MEETING_BLOCKED_BY_SABOTAGE",
    // Sabotage error codes
    ERR_SABOTAGE_FORBIDDEN: "ERR_SABOTAGE_FORBIDDEN",
    ERR_SABOTAGE_ALREADY_ACTIVE: "ERR_SABOTAGE_ALREADY_ACTIVE",
    ERR_SABOTAGE_COOLDOWN: "ERR_SABOTAGE_COOLDOWN",
    ERR_SABOTAGE_NOT_ACTIVE: "ERR_SABOTAGE_NOT_ACTIVE",
    ERR_SABOTAGE_COMMUNICATIONS_ACTIVE: "ERR_SABOTAGE_COMMUNICATIONS_ACTIVE",
    ERR_SABOTAGE_COMMUNICATIONS_QUESTS_BLOCKED: "ERR_SABOTAGE_COMMUNICATIONS_QUESTS_BLOCKED",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
