export const ERROR_CODES = {
    GAME_NOT_FOUND: "GAME_NOT_FOUND",
    ERR_SIGNAL_LOST: "ERR_SIGNAL_LOST",
    ERR_FULL_CAPACITY: "ERR_FULL_CAPACITY",
    ERR_INVALID_ALIAS: "ERR_INVALID_ALIAS",
    ERR_INVALID_SIGNATURE: "ERR_INVALID_SIGNATURE",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
